name: Executar Script de Download de JSON

on:
  schedule:
    - cron: '00 20 * * *'  # Ajuste o cron para UTC

jobs:
  baixar-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Step 1: Instalar dependências
      - name: Instalar dependências
        run: npm install
      
      # Step 2: Executar o script para baixar o JSON
      - name: Executar script de download
        run: node ./baixarCSVQueimadas.js
      
      # Step 3: Verificar arquivo na pasta public
      - name: Verificar arquivo na pasta public
        run: ls -la ./public/latest.json
