name: Executar Script de Download de CSV

on:
  schedule:
    - cron: '30 15 * * *'  # Ajuste o cron para às 8h UTC

jobs:
  baixar-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Step 1: Instalar dependências
      - name: Instalar dependências
        run: npm install
      
      # Step 2: Executar o script para baixar o CSV
      - name: Executar script de download
        run: node ./baixarCSVQueimadas.js
      
      # Step 3: Mover o arquivo para a pasta public (se necessário)
      - name: Mover arquivo para a pasta public
        run: mv /home/runner/work/firescope/firescope/public/latest.json ./public
      
      # Step 4: Confirmar que o arquivo foi movido corretamente (opcional)
      - name: Verificar arquivo na pasta public
        run: ls -la ./public/latest.json
