name: Executar Script de Download de CSV

on:
  schedule:
    - cron: '15 02 * * *'  # Ajuste o cron para o horário desejado

jobs:
  baixar-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Step 1: Instalar dependências
      - name: Instalar dependências
        run: npm install
      
      # Step 2: Executar o script para baixar o CSV e converter para JSON
      - name: Executar script de download
        run: node ./baixarCSVQueimadas.js
      
      # Step 3: Commit e push das mudanças
      - name: Adicionar alterações ao Git
        run: |
          git config --local user.email "adriano.alyson@gmail.com"
          git config --local user.name "Adriano Mendes"
          git add ./public/latest.json
          git commit -m "latest.json atualizado"
          git push -u origin main
