name: Executar Script de Download de CSV

on:
  schedule:
    - cron: '00 03 * * *'
    - cron: '00 08 * * *'
    - cron: '00 13 * * *'
    - cron: '00 18 * * *'

jobs:
  baixar-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Instala dependências
      - name: Instalar dependências
        run: npm install
      
      # Executa o script para baixar o CSV e converter para JSON
      - name: Executar script de download
        run: node ./baixarCSVQueimadas.js
      
      # Commit e push das mudanças
      - name: Adicionar alterações ao Git
        run: |
          git config --local user.email "adriano.alyson@gmail.com"
          git config --local user.name "Adriano Mendes"
          git add ./public/latest.json
          git commit -m "latest.json atualizado"
          git push -u origin main
